FROM node:22.2.0

# The application directory
WORKDIR /app

COPY package*.json /app

# this is just information not necessarilly used
EXPOSE 3000

CMD npm install --prefer-offline && \
  npm run start:dev
