version: '3'
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video_stream_service
      dockerfile: Dockerfile
    container_name: video-streaming-service
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"